do: a1 a2 a3 a4 a5 a6 a7 a8 a9 a10 a20 a30 a40 a50 a60 a70 a80 a90 a100
gen:
	gcc generate_arrays.c -o gen.exe -O2
a1: gen
	./gen.exe 1 > a1.txt
a2: gen
	./gen.exe 2 > a2.txt
a3: gen
	./gen.exe 3 > a3.txt
a4: gen
	./gen.exe 4 > a4.txt
a5: gen
	./gen.exe 5 > a5.txt
a6: gen
	./gen.exe 6 > a6.txt
a7: gen
	./gen.exe 7 > a7.txt
a8: gen
	./gen.exe 8 > a8.txt
a9: gen
	./gen.exe 9 > a9.txt
a10: gen
	./gen.exe 10 > a10.txt
a20: gen
	./gen.exe 20 > a20.txt
a30: gen
	./gen.exe 30 > a30.txt
a40: gen
	./gen.exe 40 > a40.txt
a50: gen
	./gen.exe 50 > a50.txt
a60: gen
	./gen.exe 60 > a60.txt
a70: gen
	./gen.exe 70 > a70.txt
a80: gen
	./gen.exe 80 > a80.txt
a90: gen
	./gen.exe 90 > a90.txt
a100: gen
	./gen.exe 100 > a100.txt
